### ISSUE TITLE
Tests terminate with Signal 11

### ISSUE THREAD

**Issue by yurivict** [DigitalInBlue/Celero#157]
The ```celero-test``` executable terminates with signal:

```
[...skipped...]
[----------] 2 tests from Distribution
[ RUN      ] Distribution.BuildDistribution
[       OK ] Distribution.BuildDistribution (0 ms)
[ RUN      ] Distribution.RunDistribution
[       OK ] Distribution.RunDistribution (1 ms)
[----------] 2 tests from Distribution (1 ms total)

[----------] 9 tests from Executor
[ RUN      ] Executor.RunAll
*** Signal 11

Stop.
make: stopped in /disk-samsung/freebsd-ports/benchmarks/libcelero
```

Version: 2.8.2
OS: FreeBSD 12.2

**Comment by yurivict** [comment]
@DigitalInBlue Any chance to resolve this?

**Comment by DigitalInBlue** [comment]
Resolved in v2.8.4.

**Comment by yurivict** [comment]
@DigitalInBlue The problem still exists in 2.8.5

**Comment by DigitalInBlue** [comment]
Yes.  I haven't looked at this yet.  Do you have a stack trace you can share?

**Comment by yurivict** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
Address not mapped to object.
fgets (buf=0x7fffffffe030 "\260\302.", n=128, fp=0x0) at /disk-samsung/freebsd-src/lib/libc/stdio/fgets.c:62
62		ORIENT(fp, -1);
(gdb) bt
#0  fgets (buf=0x7fffffffe030 "\260\302.", n=128, fp=0x0) at /disk-samsung/freebsd-src/lib/libc/stdio/fgets.c:62
#1  0x00000008002ec310 in celero::GetRAMVirtualUsedByCurrentProcess() () from /usr/ports/benchmarks/libcelero/work/.build/libcelero.so
#2  0x00000008002e7f8d in ExecuteProblemSpace(std::__1::shared_ptr<celero::ExperimentResult>)::$_0::operator()(bool, std::__1::shared_ptr<celero::UserDefinedMeasurementCollector>) const ()
   from /usr/ports/benchmarks/libcelero/work/.build/libcelero.so
#3  0x00000008002e7ab1 in ExecuteProblemSpace(std::__1::shared_ptr<celero::ExperimentResult>) () from /usr/ports/benchmarks/libcelero/work/.build/libcelero.so
#4  0x00000008002e8843 in celero::executor::RunBaseline(std::__1::shared_ptr<celero::Benchmark>) () from /usr/ports/benchmarks/libcelero/work/.build/libcelero.so
#5  0x00000008002e8195 in celero::executor::RunAllBaselines() () from /usr/ports/benchmarks/libcelero/work/.build/libcelero.so
#6  0x00000008002e80e9 in celero::executor::RunAll() () from /usr/ports/benchmarks/libcelero/work/.build/libcelero.so
#7  0x0000000000225a58 in Executor_RunAll_Test::TestBody() ()
#8  0x0000000800364ed0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
   from /usr/local/lib/libgtest.so.1.12.1
#9  0x000000080034a7ab in testing::Test::Run() () from /usr/local/lib/libgtest.so.1.12.1
#10 0x000000080034b439 in testing::TestInfo::Run() () from /usr/local/lib/libgtest.so.1.12.1
#11 0x000000080034be95 in testing::TestSuite::Run() () from /usr/local/lib/libgtest.so.1.12.1
#12 0x000000080035c95f in testing::internal::UnitTestImpl::RunAllTests() () from /usr/local/lib/libgtest.so.1.12.1
#13 0x00000008003659f0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) () from /usr/local/lib/libgtest.so.1.12.1
#14 0x000000080035bff3 in testing::UnitTest::Run() () from /usr/local/lib/libgtest.so.1.12.1
#15 0x00000008002ae89d in main () from /usr/local/lib/libgtest_main.so.1.12.1
#16 0x0000000000216720 in _start (ap=<optimized out>, cleanup=<optimized out>) at /disk-samsung/freebsd-src/lib/csu/amd64/crt1_c.c:75
(gdb) 
```
